version: 2
workflows:
  version: 2
  run_tests:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/php:7.1.5-browsers

    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
          - composer-dev-v1-{{ checksum "composer.json" }}

      - run: composer install --classmap-authoritative

      - save_cache:
          paths:
            - ./vendor
          key: composer-dev-v1-{{ checksum "composer.json" }}

      - run: if [ -f vendor/bin/phpunit ]; then vendor/bin/phpunit; fi
      - run: if [ -f vendor/bin/pharmacist ]; then vendor/bin/pharmacist; fi
      - run: if [ -f vendor/bin/phpstan ]; then php -d memory_limit=4G vendor/bin/phpstan analyse -l 0 src; fi